HttpClientConfig:
  read_timeout: "30s"
  write_timeout: "30s"
  max_idle_conn_duration: "5s"
  max_conns_per_host: 200
  http_concurrency: 2048
  dns_cache_duration: "1800s"

KafkaConfigs:
  - cluster: test-kafka-cluster
    brokers: hostname:9092
    writer_buffer_size: 100
    writer_max_retries: 3
    writer_batch_bytes: 10485760
    writer_batch_size: 100
    writer_batch_frequency: "3s"
    writer_timeout: "10s"
    reader_max_bytes: 10485760
    reader_queue_capacity: 100
    reader_max_wait: "10s"
    reader_read_batch_timeout: "10s"
    reader_max_attempts: 5

DorisConfigs:
  - cluster: doris-cluster-product
    fe_nodes: "hostname-prd:8030"
    username: admin
    password: your_pwd
    write_timeout: "10s"
  - cluster: doris-cluster-dev
    fe_nodes: "hostname-dev:8030"
    username: root
    password: your_pwd
    write_timeout: "10s"

EtlConfigs:
  - job_name: sample_job
    job_owner: qjj
    source_kafka_cluster: test-kafka-cluster
    source_kafka_data_protocol: json
    source_kafka_data_explode_keys: ed,qjj  # split by ,
    source_kafka_topic: qjj
    source_kafka_group: group
    sink_doris_cluster: doris-cluster-dev
    sink_doris_table: test.qjj_test
    sink_doris_lowercase_column_enabled: true
    sink_doris_column_aggr: {"enabled": false, "aggr_types": {"DORIS_ALL_COLUMNS": "REPLACE_IF_NOT_NULL","aggr_col1": "REPLACE_IF_NOT_NULL", "aggr_col2": "REPLACE_IF_NOT_NULL"}}
    sink_doris_column_mapping: {"aaa": "@aaa","rGuid": "r_guid"}
    sink_max_retries: 5
    sink_retry_interval: "3s"
    sink_batch_size: 6
    sink_batch_bytes: 104857600
    sink_batch_interval: "3s"
    sink_max_filter_ratio: 0.005

alert_web_hook: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxx